# -*- mode: restclient -*-
# Emacs restclient examples for the Activities application

# Variables
:host  = http://localhost:5387
:id    = 9d70e4e9-4863-4457-8523-79d3f14c8454
:title = Hello from Emacs

:form-header = <<
Content-Type: application/x-www-form-urlencoded
#

# LIST ACTIVITIES
GET :host/activities

# NEW ACTIVITY FORM
GET :host/activities/new

# NEW ACTIVITY
POST :host/activities
:form-header

title=:title

# ACTIVITY
GET :host/activity/:id

# EDIT ACTIVITY FORM
GET :host/activity/:id/edit

# EDIT ACTIVITY
POST :host/activities/activity/:id
:form-header

title=EDITED

# DELETE ACTIVITY
DELETE :host/activity/:id
